why-admint-slider
FifthTry/admint.io pull request #13
Opened 2023-03-29 05:37 UTC by priyanka9634

why-admint-slider

2023-03-29 12:11 UTC, gsalunke commented
@priyanka9634 Below are UI review comments:

**Desktop View:**

- [ ]  Slide - 1 - image position is wrong, move it to top.

2023-03-30 06:31 UTC, Arpita-Jaiswal requested changes

2023-03-30 06:31 UTC, Arpita-Jaiswal commented on common/fonts.ftd
> +mobile: $size-24-regular-desktop
```suggestion
-- ftd.type size-24-regular:
line-height.px: 36
size.px: 24
letter-spacing.px: 0
weight: 400
font-family: $nunito-assets.fonts.Nunito
```

2023-03-30 06:42 UTC, Arpita-Jaiswal approved these changes

2023-03-30 06:44 UTC, gsalunke approved these changes

2023-03-30 06:58 UTC, merged